/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iutils_pattern_observer_LoginService */

#ifndef _Included_com_iutils_pattern_observer_LoginService
#define _Included_com_iutils_pattern_observer_LoginService
#ifdef __cplusplus
extern "C" {
#endif

JavaVM *gJavaVM;
jobject gJavaObj;

/*
 * Class:     com_iutils_pattern_observer_LoginService
 * Method:    initSDK
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_iutils_pattern_observer_LoginService_initSDK
        (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_iutils_pattern_observer_LoginService
 * Method:    login
 * Signature: (Lcom/iutils/pattern/observer/LoginParam;)V
 */
JNIEXPORT void JNICALL Java_com_iutils_pattern_observer_LoginService_login
        (JNIEnv *, jobject, jobject);

static void* ocxCallback(void *arg);

#ifdef __cplusplus
}
#endif
#endif
