/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iutils_framework_JniTest */

#ifndef _Included_com_iutils_framework_JniTest
#define _Included_com_iutils_framework_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iutils_framework_JniTest
 * Method:    getPackageName
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iutils_framework_JniTest_getPackageName
  (JNIEnv *, jclass, jobject);

/**
 * public native int[][] get2Array(int dimon);
 */
JNIEXPORT jobjectArray JNICALL Java_com_iutils_framework_JniTest_get2Array
        (JNIEnv *, jobject, jint);

/**
 * Class:     com_iutils_framework_JniTest
 * public native Task getTask();
 */
JNIEXPORT jobject JNICALL Java_com_iutils_framework_JniTest_getTask
        (JNIEnv *, jobject);

/**
 * Class:     com_iutils_framework_JniTest
 * public native ArrayList<Task> getTaskList();
 */
JNIEXPORT jobject JNICALL Java_com_iutils_framework_JniTest_getTaskList
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
