/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iutils_framework_JniTest */

#ifndef _Included_com_iutils_framework_JniTest
#define _Included_com_iutils_framework_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iutils_framework_JniTest
 * Method:    getPackageName
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iutils_framework_JniTest_getPackageName
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
